### ISSUE TITLE
How do you define the *low* vs *high* level?

### ISSUE THREAD

**Issue by nnop** [sair-lab/iSLAM#2]
Great idea for self-supervised SLAM!
I have a question about how do you define the **low** vs **high** for level.
Is it because BA optimize against the raw image observation, while deep networks learns the high level feature?

But in another perspective, BA seems more high level for it's closer to the final purpose, while feature matching is more low level for it's doing raw image feature matching.

Hope to know about your definitions for this.
@wang-chen

**Comment by wang-chen** [comment]
Hi, a high-level answer is: an upper-level optimization targets tasks that are suitable for learning-based methods, while low-level optimization targets tasks that are suitable for geometry-based methods.

**Comment by FuTaimeng** [comment]
Thanks for your interest in our work!

Since there haven't been any new comments for a while, I'll close this issue.
